language: node_js
node_js:
  - 4
  - 6
git:
  depth: 10
branches:
  only:
    - master
before_install:
  - '[ "${TRAVIS_NODE_VERSION}" != "0.8" ] || npm install -g npm@1.4.28'
  - npm install -g npm
  - npm --version
sudo: false